// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import NestedFormController from "./nested_form_controller.js";
import HelloController from "./hello_controller";
import MarkdownEditorController from "./markdown_editor_controller.js";
import CpModalController from "./cp_modal_controller.js";
import MoneyModalController from "./money_modal_controller.js";
import EquipmentModalController from "./equipment_modal_controller.js";
import NotesModalController from "./notes_modal_controller.js";
import EditNotesModalController from "./edit_notes_modal_controller.js";

application.register("nested-form", NestedFormController);
application.register("hello", HelloController);
application.register("markdown-editor", MarkdownEditorController);
application.register("cp-modal", CpModalController);
application.register("money-modal", MoneyModalController);
application.register("equipment-modal", EquipmentModalController);
application.register("notes-modal", NotesModalController);
application.register("edit-notes-modal", EditNotesModalController);

import "./railsui";
