// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import NestedFormController from "./nested_form_controller.js";
import HelloController from "./hello_controller";
import MarkdownEditorController from "./markdown_editor_controller.js";
import CpModalController from "./cp_modal_controller.js";
import MoneyModalController from "./money_modal_controller.js";
import EquipmentModalController from "./equipment_modal_controller.js";
import AttributeModalController from "./attribute_modal_controller.js";
import DefectModalController from "./defect_modal_controller.js";
import NotesModalController from "./notes_modal_controller.js";
import EditNotesModalController from "./edit_notes_modal_controller.js";
import EditAttributeModalController from "./edit_attribute_modal_controller.js";
import EditEquipmentModalController from "./edit_equipment_modal_controller.js";
import EditDefectModalController from "./edit_defect_modal_controller.js";
import FlashController from "./flash_controller.js";

application.register("nested-form", NestedFormController);
application.register("hello", HelloController);
application.register("markdown-editor", MarkdownEditorController);
application.register("cp-modal", CpModalController);
application.register("money-modal", MoneyModalController);
application.register("equipment-modal", EquipmentModalController);
application.register("attribute-modal", AttributeModalController);
application.register("defect-modal", DefectModalController);
application.register("notes-modal", NotesModalController);
application.register("edit-notes-modal", EditNotesModalController);
application.register("edit-attribute-modal", EditAttributeModalController);
application.register("edit-equipment-modal", EditEquipmentModalController);
application.register("edit-defect-modal", EditDefectModalController);
application.register("flash", FlashController);

import "./railsui";
